In [1]:
import os
os.environ['CUDA_VISIBLE_DEVICES'] = '0'
import pandas as pd
import driver_genes as dg
dg.set_verbosity(False)

from driver_genes.pipelines import Pipeline
from driver_genes.myutils import render_template

## load job info and config template

The config template is a yaml file that contains the placeholder of parameters for the experiment.

changable parameters: 
- In job info: job_name, split_version, adata_file, split_file, layer_name, subset_name
- Additional: output_dir

In [ ]:
job_info_df = pd.read_csv('job_info_benchmark.csv')
config_template_path = "config_template.yaml"

# specify other experiment parameters
output_dir = '../results/benchmarking'

In [ ]:
for info_dict in job_info_df.to_dict(orient='records'):
    print(info_dict)
    config_dict = render_template(config_template_path, **info_dict, output_dir=output_dir)
    pipeline = Pipeline(config_dict=config_dict)
    pipeline.fit()
    pipeline.save_best_model()
    metrics_df, adata_pred = pipeline.evaluate(num_results=5, concat=True, agg=True)
    metrics_df.to_csv(os.path.join(pipeline.args.trainer.output_dir, 'test_epoch_metrics.csv'), index=False)
    os.makedirs(os.path.join(pipeline.args.trainer.output_dir, 'anndata'), exist_ok=True)
    for key in adata_pred.keys():
        adata_pred[key].write(os.path.join(
            pipeline.args.trainer.output_dir, 
            'anndata', 
            f'{key}.h5ad'
        ))
    break

{'job_name': 'schmidt_tutorial', 'split_version': 'stimulated', 'adata_file': 'preprocessed.h5ad', 'split_file': 'split_trainonstimulated.csv', 'layer_name': 'X', 'subset_name': 'highly_variable'}

GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
HPU available: False, using: 0 HPUs
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0,1,2]

  | Name               | Type                 | Params | Mode
--------------------------------------------------------------------
0 | model              | DriverGeneFinder     | 5.9 M  | train
1 | train_metrics_func | MetricCollection     | 0      | train
2 | val_metrics_func   | MetricCollection     | 0      | train
3 | test_metrics_func  | MetricCollection     | 0      | train
4 | mixing_losses      | UncertaintyWeighting | 3      | train
--------------------------------------------------------------------
5.9 M     Trainable params
0         Non-trainable params
5.9 M     Total params
23.441    Total estimated model params size (MB)
65        Modules in train mode
0         Modules in eval mode

Sanity Checking: |          | 0/? [00:00<?, ?it/s]

Training: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0,1,2]

Testing: |          | 0/? [00:00<?, ?it/s]

LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0,1,2]

────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
                    Test metric                                       DataLoader 0
────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
                   ACC@Top1/Te/a                                   0.8197081685066223
      ACC@Top1/Te/preprocessed_Re-stimulated                       0.9144834876060486
         ACC@Top1/Te/preprocessed_Resting                           0.724932849407196
                   ACC@Top5/Te/a                                   0.9520279765129089
      ACC@Top5/Te/preprocessed_Re-stimulated                       0.9831894636154175
         ACC@Top5/Te/preprocessed_Resting                          0.9208664894104004
                   Coverage/Te/a                                   1.9646618366241455
      Coverage/Te/preprocessed_Re-stimulated                       1.4597722291946411
         Coverage/Te/preprocessed_Resting                          2.4695513248443604
                     Lcls/Te/a                                      2.727722406387329
        Lcls/Te/preprocessed_Re-stimulated                          1.715415596961975
           Lcls/Te/preprocessed_Resting                            3.7400290966033936
                    Lcls_w/Te/a                                     978.7532958984375
                     Lkld/Te/a                                             0.0
        Lkld/Te/preprocessed_Re-stimulated                                 0.0
           Lkld/Te/preprocessed_Resting                                    0.0
                     Lmix/Te/a                                      3270.279052734375
                     Lrec/Te/a                                      714.938720703125
        Lrec/Te/preprocessed_Re-stimulated                          540.1510009765625
           Lrec/Te/preprocessed_Resting                             889.7263793945312
                     Lvae/Te/a                                      714.938720703125
        Lvae/Te/preprocessed_Re-stimulated                          540.1510009765625
           Lvae/Te/preprocessed_Resting                             889.7263793945312
                    Lvae_w/Te/a                                    0.8493526577949524
                     MRR/Te/a                                      0.8772386312484741
         MRR/Te/preprocessed_Re-stimulated                         0.9440819025039673
            MRR/Te/preprocessed_Resting                            0.8103952407836914
                 RankingLoss/Te/a                                 0.014186202548444271
     RankingLoss/Te/preprocessed_Re-stimulated                    0.0067613557912409306
        RankingLoss/Te/preprocessed_Resting                       0.021611051633954048
                    RelPos/Te/a                                    0.9858137965202332
       RelPos/Te/preprocessed_Re-stimulated                        0.9932386875152588
          RelPos/Te/preprocessed_Resting                           0.9783889651298523
                 label#AUPRC/Te/a                                   0.908681333065033
     label#AUPRC/Te/preprocessed_Re-stimulated                     0.9335460662841797
        label#AUPRC/Te/preprocessed_Resting                        0.8838167786598206
                 label#AUROC/Te/a                                  0.9929251670837402
     label#AUROC/Te/preprocessed_Re-stimulated                     0.9939520955085754
        label#AUROC/Te/preprocessed_Resting                        0.9918982982635498
                   label#F1/Te/a                                   0.5327571630477905
      label#F1/Te/preprocessed_Re-stimulated                       0.6782309412956238
         label#F1/Te/preprocessed_Resting                          0.3872835636138916
               label#Precision/Te/a                                0.8091417551040649
   label#Precision/Te/preprocessed_Re-stimulated                   0.9158755540847778
      label#Precision/Te/preprocessed_Resting                      0.7024080753326416
                 label#Recall/Te/a                                 0.43779411911964417
    label#Recall/Te/preprocessed_Re-stimulated                     0.5749598145484924
       label#Recall/Te/preprocessed_Resting                        0.3006284832954407
                     nDCG/Te/a                                     0.9059047102928162
        nDCG/Te/preprocessed_Re-stimulated                          0.957209050655365
           nDCG/Te/preprocessed_Resting                            0.8546004295349121
                 sample#AUPRC/Te/a                                 0.8772386908531189
    sample#AUPRC/Te/preprocessed_Re-stimulated                     0.9440819621086121
       sample#AUPRC/Te/preprocessed_Resting                         0.810395359992981
                 sample#AUROC/Te/a                                 0.9858137965202332
    sample#AUROC/Te/preprocessed_Re-stimulated                     0.9932386875152588
       sample#AUROC/Te/preprocessed_Resting                        0.9783890247344971
                sample#F1@Top1/Te/a                                0.8197081685066223
   sample#F1@Top1/Te/preprocessed_Re-stimulated                    0.9144834876060486
      sample#F1@Top1/Te/preprocessed_Resting                        0.724932849407196
                sample#F1@Top5/Te/a                                0.3173426687717438
   sample#F1@Top5/Te/preprocessed_Re-stimulated                    0.32772985100746155
      sample#F1@Top5/Te/preprocessed_Resting                       0.3069555461406708
            sample#Precision@Top1/Te/a                             0.8197081685066223
sample#Precision@Top1/Te/preprocessed_Re-stimulated                0.9144834876060486
   sample#Precision@Top1/Te/preprocessed_Resting                    0.724932849407196
            sample#Precision@Top5/Te/a                             0.19040559232234955
sample#Precision@Top5/Te/preprocessed_Re-stimulated                0.19663789868354797
   sample#Precision@Top5/Te/preprocessed_Resting                   0.18417327105998993
              sample#Recall@Top1/Te/a                              0.8197081685066223
 sample#Recall@Top1/Te/preprocessed_Re-stimulated                  0.9144834876060486
    sample#Recall@Top1/Te/preprocessed_Resting                      0.724932849407196
              sample#Recall@Top5/Te/a                              0.9520279765129089
 sample#Recall@Top5/Te/preprocessed_Re-stimulated                   0.983189582824707
    sample#Recall@Top5/Te/preprocessed_Resting                     0.9208664894104004
────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────

Testing: |          | 0/? [00:00<?, ?it/s]

LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0,1,2]

────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
                    Test metric                                       DataLoader 0
────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
                   ACC@Top1/Te/a                                    0.824183464050293
      ACC@Top1/Te/preprocessed_Re-stimulated                       0.9226011037826538
         ACC@Top1/Te/preprocessed_Resting                          0.7257658839225769
                   ACC@Top5/Te/a                                   0.9502862095832825
      ACC@Top5/Te/preprocessed_Re-stimulated                       0.9852123260498047
         ACC@Top5/Te/preprocessed_Resting                          0.9153599739074707
                   Coverage/Te/a                                   1.9225579500198364
      Coverage/Te/preprocessed_Re-stimulated                       1.4218069314956665
         Coverage/Te/preprocessed_Resting                           2.423308849334717
                     Lcls/Te/a                                      2.72037410736084
        Lcls/Te/preprocessed_Re-stimulated                         1.6925842761993408
           Lcls/Te/preprocessed_Resting                             3.748164415359497
                    Lcls_w/Te/a                                     978.7532958984375
                     Lkld/Te/a                                             0.0
        Lkld/Te/preprocessed_Re-stimulated                                 0.0
           Lkld/Te/preprocessed_Resting                                    0.0
                     Lmix/Te/a                                       3264.4072265625
                     Lrec/Te/a                                      716.492431640625
        Lrec/Te/preprocessed_Re-stimulated                          539.8594360351562
           Lrec/Te/preprocessed_Resting                             893.1253662109375
                     Lvae/Te/a                                      716.492431640625
        Lvae/Te/preprocessed_Re-stimulated                          539.8594360351562
           Lvae/Te/preprocessed_Resting                             893.1253662109375
                    Lvae_w/Te/a                                    0.8493526577949524
                     MRR/Te/a                                      0.8810298442840576
         MRR/Te/preprocessed_Re-stimulated                         0.9496147036552429
            MRR/Te/preprocessed_Resting                            0.8124449849128723
                 RankingLoss/Te/a                                 0.013567029498517513
     RankingLoss/Te/preprocessed_Re-stimulated                     0.00620304374024272
        RankingLoss/Te/preprocessed_Resting                        0.02093101479113102
                    RelPos/Te/a                                    0.9864330291748047
       RelPos/Te/preprocessed_Re-stimulated                        0.9937970042228699
          RelPos/Te/preprocessed_Resting                            0.97906893491745
                 label#AUPRC/Te/a                                  0.9077800512313843
     label#AUPRC/Te/preprocessed_Re-stimulated                     0.9306651949882507
        label#AUPRC/Te/preprocessed_Resting                        0.8848947882652283
                 label#AUROC/Te/a                                  0.9925433993339539
     label#AUROC/Te/preprocessed_Re-stimulated                     0.9941882491111755
        label#AUROC/Te/preprocessed_Resting                        0.9908984899520874
                   label#F1/Te/a                                   0.5362746119499207
      label#F1/Te/preprocessed_Re-stimulated                       0.6839064359664917
         label#F1/Te/preprocessed_Resting                          0.3886427879333496
               label#Precision/Te/a                                0.8153170347213745
   label#Precision/Te/preprocessed_Re-stimulated                    0.921610414981842
      label#Precision/Te/preprocessed_Resting                      0.7090237140655518
                 label#Recall/Te/a                                 0.43894287943840027
    label#Recall/Te/preprocessed_Re-stimulated                     0.5794227719306946
       label#Recall/Te/preprocessed_Resting                        0.29846295714378357
                     nDCG/Te/a                                     0.9088419079780579
        nDCG/Te/preprocessed_Re-stimulated                         0.9614462852478027
           nDCG/Te/preprocessed_Resting                            0.8562373518943787
                 sample#AUPRC/Te/a                                 0.8810300230979919
    sample#AUPRC/Te/preprocessed_Re-stimulated                     0.9496148228645325
       sample#AUPRC/Te/preprocessed_Resting                        0.8124451041221619
                 sample#AUROC/Te/a                                 0.9864330291748047
    sample#AUROC/Te/preprocessed_Re-stimulated                     0.9937970042228699
       sample#AUROC/Te/preprocessed_Resting                        0.9790690541267395
                sample#F1@Top1/Te/a                                 0.824183464050293
   sample#F1@Top1/Te/preprocessed_Re-stimulated                    0.9226011037826538
      sample#F1@Top1/Te/preprocessed_Resting                       0.7257658839225769
                sample#F1@Top5/Te/a                                0.3167620897293091
   sample#F1@Top5/Te/preprocessed_Re-stimulated                    0.32840415835380554
      sample#F1@Top5/Te/preprocessed_Resting                        0.305120050907135
            sample#Precision@Top1/Te/a                              0.824183464050293
sample#Precision@Top1/Te/preprocessed_Re-stimulated                0.9226011037826538
   sample#Precision@Top1/Te/preprocessed_Resting                   0.7257658839225769
            sample#Precision@Top5/Te/a                             0.19005723297595978
sample#Precision@Top5/Te/preprocessed_Re-stimulated                0.19704246520996094
   sample#Precision@Top5/Te/preprocessed_Resting                   0.18307200074195862
              sample#Recall@Top1/Te/a                               0.824183464050293
 sample#Recall@Top1/Te/preprocessed_Re-stimulated                  0.9226011037826538
    sample#Recall@Top1/Te/preprocessed_Resting                     0.7257658839225769
              sample#Recall@Top5/Te/a                              0.9502862095832825
 sample#Recall@Top5/Te/preprocessed_Re-stimulated                  0.9852123260498047
    sample#Recall@Top5/Te/preprocessed_Resting                     0.9153600931167603
────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────

Testing: |          | 0/? [00:00<?, ?it/s]

LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0,1,2]

────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
                    Test metric                                       DataLoader 0
────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
                   ACC@Top1/Te/a                                   0.8278473019599915
      ACC@Top1/Te/preprocessed_Re-stimulated                        0.919463574886322
         ACC@Top1/Te/preprocessed_Resting                          0.7362310290336609
                   ACC@Top5/Te/a                                   0.9531838297843933
      ACC@Top5/Te/preprocessed_Re-stimulated                       0.9829187393188477
         ACC@Top5/Te/preprocessed_Resting                          0.9234489798545837
                   Coverage/Te/a                                   1.9379732608795166
      Coverage/Te/preprocessed_Re-stimulated                       1.5458900928497314
         Coverage/Te/preprocessed_Resting                          2.3300564289093018
                     Lcls/Te/a                                      2.67636775970459
        Lcls/Te/preprocessed_Re-stimulated                         1.6461429595947266
           Lcls/Te/preprocessed_Resting                             3.706592321395874
                    Lcls_w/Te/a                                     978.7532958984375
                     Lkld/Te/a                                             0.0
        Lkld/Te/preprocessed_Re-stimulated                                 0.0
           Lkld/Te/preprocessed_Resting                                    0.0
                     Lmix/Te/a                                      3220.29541015625
                     Lrec/Te/a                                      715.2681274414062
        Lrec/Te/preprocessed_Re-stimulated                          543.1883544921875
           Lrec/Te/preprocessed_Resting                             887.347900390625
                     Lvae/Te/a                                      715.2681274414062
        Lvae/Te/preprocessed_Re-stimulated                          543.1883544921875
           Lvae/Te/preprocessed_Resting                             887.347900390625
                    Lvae_w/Te/a                                    0.8493526577949524
                     MRR/Te/a                                       0.882621169090271
         MRR/Te/preprocessed_Re-stimulated                         0.9463829398155212
            MRR/Te/preprocessed_Resting                            0.8188593983650208
                 RankingLoss/Te/a                                 0.013793723657727242
     RankingLoss/Te/preprocessed_Re-stimulated                     0.00802779570221901
        RankingLoss/Te/preprocessed_Resting                       0.019559655338525772
                    RelPos/Te/a                                    0.9862062931060791
       RelPos/Te/preprocessed_Re-stimulated                        0.9919721484184265
          RelPos/Te/preprocessed_Resting                           0.9804403781890869
                 label#AUPRC/Te/a                                  0.9054018259048462
     label#AUPRC/Te/preprocessed_Re-stimulated                     0.9319915771484375
        label#AUPRC/Te/preprocessed_Resting                        0.8788120150566101
                 label#AUROC/Te/a                                  0.9918099045753479
     label#AUROC/Te/preprocessed_Re-stimulated                     0.9928810000419617
        label#AUROC/Te/preprocessed_Resting                        0.9907389283180237
                   label#F1/Te/a                                   0.5403964519500732
      label#F1/Te/preprocessed_Re-stimulated                       0.6956852078437805
         label#F1/Te/preprocessed_Resting                          0.38510772585868835
               label#Precision/Te/a                                0.8106517791748047
   label#Precision/Te/preprocessed_Re-stimulated                   0.9110493659973145
      label#Precision/Te/preprocessed_Resting                      0.7102540731430054
                 label#Recall/Te/a                                 0.4472854733467102
    label#Recall/Te/preprocessed_Re-stimulated                     0.5985293388366699
       label#Recall/Te/preprocessed_Resting                        0.2960416376590729
                     nDCG/Te/a                                     0.9100033044815063
        nDCG/Te/preprocessed_Re-stimulated                         0.9587633013725281
           nDCG/Te/preprocessed_Resting                            0.8612433075904846
                 sample#AUPRC/Te/a                                 0.8826212286949158
    sample#AUPRC/Te/preprocessed_Re-stimulated                     0.9463829398155212
       sample#AUPRC/Te/preprocessed_Resting                        0.8188595771789551
                 sample#AUROC/Te/a                                 0.9862062931060791
    sample#AUROC/Te/preprocessed_Re-stimulated                     0.9919722080230713
       sample#AUROC/Te/preprocessed_Resting                        0.9804403781890869
                sample#F1@Top1/Te/a                                0.8278473019599915
   sample#F1@Top1/Te/preprocessed_Re-stimulated                     0.919463574886322
      sample#F1@Top1/Te/preprocessed_Resting                       0.7362310886383057
                sample#F1@Top5/Te/a                                0.3177279531955719
   sample#F1@Top5/Te/preprocessed_Re-stimulated                    0.3276395797729492
      sample#F1@Top5/Te/preprocessed_Resting                       0.3078163266181946
            sample#Precision@Top1/Te/a                             0.8278473019599915
sample#Precision@Top1/Te/preprocessed_Re-stimulated                 0.919463574886322
   sample#Precision@Top1/Te/preprocessed_Resting                   0.7362310886383057
            sample#Precision@Top5/Te/a                             0.1906367540359497
sample#Precision@Top5/Te/preprocessed_Re-stimulated                0.19658371806144714
   sample#Precision@Top5/Te/preprocessed_Resting                   0.18468980491161346
              sample#Recall@Top1/Te/a                              0.8278473019599915
 sample#Recall@Top1/Te/preprocessed_Re-stimulated                   0.919463574886322
    sample#Recall@Top1/Te/preprocessed_Resting                     0.7362310886383057
              sample#Recall@Top5/Te/a                              0.9531838893890381
 sample#Recall@Top5/Te/preprocessed_Re-stimulated                  0.9829187393188477
    sample#Recall@Top5/Te/preprocessed_Resting                     0.9234489798545837
────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────

Testing: |          | 0/? [00:00<?, ?it/s]

LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0,1,2]

────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
                    Test metric                                       DataLoader 0
────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
                   ACC@Top1/Te/a                                   0.8249135613441467
      ACC@Top1/Te/preprocessed_Re-stimulated                       0.9266914129257202
         ACC@Top1/Te/preprocessed_Resting                          0.7231355309486389
                   ACC@Top5/Te/a                                   0.9537649154663086
      ACC@Top5/Te/preprocessed_Re-stimulated                       0.9881185293197632
         ACC@Top5/Te/preprocessed_Resting                          0.9194114208221436
                   Coverage/Te/a                                   1.9262763261795044
      Coverage/Te/preprocessed_Re-stimulated                        1.378702998161316
         Coverage/Te/preprocessed_Resting                          2.4738497734069824
                     Lcls/Te/a                                      2.658430814743042
        Lcls/Te/preprocessed_Re-stimulated                          1.580049991607666
           Lcls/Te/preprocessed_Resting                             3.736811876296997
                    Lcls_w/Te/a                                     978.7532958984375
                     Lkld/Te/a                                             0.0
        Lkld/Te/preprocessed_Re-stimulated                                 0.0
           Lkld/Te/preprocessed_Resting                                    0.0
                     Lmix/Te/a                                       3206.4990234375
                     Lrec/Te/a                                       719.6943359375
        Lrec/Te/preprocessed_Re-stimulated                          545.1795043945312
           Lrec/Te/preprocessed_Resting                             894.209228515625
                     Lvae/Te/a                                       719.6943359375
        Lvae/Te/preprocessed_Re-stimulated                          545.1795043945312
           Lvae/Te/preprocessed_Resting                             894.209228515625
                    Lvae_w/Te/a                                    0.8493526577949524
                     MRR/Te/a                                      0.8817148208618164
         MRR/Te/preprocessed_Re-stimulated                         0.9528529644012451
            MRR/Te/preprocessed_Resting                            0.8105767965316772
                 RankingLoss/Te/a                                 0.013621713034808636
     RankingLoss/Te/preprocessed_Re-stimulated                    0.005569160915911198
        RankingLoss/Te/preprocessed_Resting                        0.0216742642223835
                    RelPos/Te/a                                    0.9863782525062561
       RelPos/Te/preprocessed_Re-stimulated                        0.9944308996200562
          RelPos/Te/preprocessed_Resting                           0.9783257246017456
                 label#AUPRC/Te/a                                  0.9103303551673889
     label#AUPRC/Te/preprocessed_Re-stimulated                     0.9395393133163452
        label#AUPRC/Te/preprocessed_Resting                        0.8811215162277222
                 label#AUROC/Te/a                                  0.9927613735198975
     label#AUROC/Te/preprocessed_Re-stimulated                     0.9948365092277527
        label#AUROC/Te/preprocessed_Resting                        0.9906861782073975
                   label#F1/Te/a                                   0.5463289022445679
      label#F1/Te/preprocessed_Re-stimulated                       0.7098178267478943
         label#F1/Te/preprocessed_Resting                          0.38283997774124146
               label#Precision/Te/a                                0.8143807053565979
   label#Precision/Te/preprocessed_Re-stimulated                   0.9397686719894409
      label#Precision/Te/preprocessed_Resting                      0.6889927387237549
                 label#Recall/Te/a                                 0.45204970240592957
    label#Recall/Te/preprocessed_Re-stimulated                     0.6074882745742798
       label#Recall/Te/preprocessed_Resting                        0.2966110110282898
                     nDCG/Te/a                                      0.90940922498703
        nDCG/Te/preprocessed_Re-stimulated                         0.9640081524848938
           nDCG/Te/preprocessed_Resting                            0.8548104166984558
                 sample#AUPRC/Te/a                                 0.8817149996757507
    sample#AUPRC/Te/preprocessed_Re-stimulated                     0.9528530240058899
       sample#AUPRC/Te/preprocessed_Resting                        0.8105769157409668
                 sample#AUROC/Te/a                                 0.9863782525062561
    sample#AUROC/Te/preprocessed_Re-stimulated                     0.9944308996200562
       sample#AUROC/Te/preprocessed_Resting                        0.9783257246017456
                sample#F1@Top1/Te/a                                0.8249135613441467
   sample#F1@Top1/Te/preprocessed_Re-stimulated                    0.9266914129257202
      sample#F1@Top1/Te/preprocessed_Resting                       0.7231355905532837
                sample#F1@Top5/Te/a                                0.3179216682910919
   sample#F1@Top5/Te/preprocessed_Re-stimulated                    0.3293727934360504
      sample#F1@Top5/Te/preprocessed_Resting                       0.30647048354148865
            sample#Precision@Top1/Te/a                             0.8249135613441467
sample#Precision@Top1/Te/preprocessed_Re-stimulated                0.9266914129257202
   sample#Precision@Top1/Te/preprocessed_Resting                   0.7231355905532837
            sample#Precision@Top5/Te/a                             0.1907529979944229
sample#Precision@Top5/Te/preprocessed_Re-stimulated                0.19762371480464935
   sample#Precision@Top5/Te/preprocessed_Resting                   0.18388229608535767
              sample#Recall@Top1/Te/a                              0.8249135613441467
 sample#Recall@Top1/Te/preprocessed_Re-stimulated                  0.9266914129257202
    sample#Recall@Top1/Te/preprocessed_Resting                     0.7231355905532837
              sample#Recall@Top5/Te/a                              0.9537649154663086
 sample#Recall@Top5/Te/preprocessed_Re-stimulated                  0.9881185293197632
    sample#Recall@Top5/Te/preprocessed_Resting                     0.9194114208221436
────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────

Testing: |          | 0/? [00:00<?, ?it/s]

LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0,1,2]

────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
                    Test metric                                       DataLoader 0
────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
                   ACC@Top1/Te/a                                   0.8237733244895935
      ACC@Top1/Te/preprocessed_Re-stimulated                       0.9185508489608765
         ACC@Top1/Te/preprocessed_Resting                          0.7289957404136658
                   ACC@Top5/Te/a                                    0.95173180103302
      ACC@Top5/Te/preprocessed_Re-stimulated                       0.9852145910263062
         ACC@Top5/Te/preprocessed_Resting                          0.9182488918304443
                   Coverage/Te/a                                    1.919284701347351
      Coverage/Te/preprocessed_Re-stimulated                       1.4462405443191528
         Coverage/Te/preprocessed_Resting                           2.392328977584839
                     Lcls/Te/a                                      2.708723545074463
        Lcls/Te/preprocessed_Re-stimulated                         1.6835399866104126
           Lcls/Te/preprocessed_Resting                             3.733907699584961
                    Lcls_w/Te/a                                     978.7532958984375
                     Lkld/Te/a                                             0.0
        Lkld/Te/preprocessed_Re-stimulated                                 0.0
           Lkld/Te/preprocessed_Resting                                    0.0
                     Lmix/Te/a                                        3253.04296875
                     Lrec/Te/a                                      716.5382690429688
        Lrec/Te/preprocessed_Re-stimulated                          542.5499877929688
           Lrec/Te/preprocessed_Resting                             890.5265502929688
                     Lvae/Te/a                                      716.5382690429688
        Lvae/Te/preprocessed_Re-stimulated                          542.5499877929688
           Lvae/Te/preprocessed_Resting                             890.5265502929688
                    Lvae_w/Te/a                                    0.8493526577949524
                     MRR/Te/a                                      0.8795943856239319
         MRR/Te/preprocessed_Re-stimulated                         0.9464243650436401
            MRR/Te/preprocessed_Resting                            0.8127642869949341
                 RankingLoss/Te/a                                 0.013518894091248512
     RankingLoss/Te/preprocessed_Re-stimulated                    0.006562358234077692
        RankingLoss/Te/preprocessed_Resting                        0.02047542668879032
                    RelPos/Te/a                                    0.9864811897277832
       RelPos/Te/preprocessed_Re-stimulated                         0.993437647819519
          RelPos/Te/preprocessed_Resting                           0.9795244932174683
                 label#AUPRC/Te/a                                   0.907504677772522
     label#AUPRC/Te/preprocessed_Re-stimulated                     0.9323230981826782
        label#AUPRC/Te/preprocessed_Resting                        0.8826863169670105
                 label#AUROC/Te/a                                  0.9928573966026306
     label#AUROC/Te/preprocessed_Re-stimulated                      0.994027853012085
        label#AUROC/Te/preprocessed_Resting                        0.9916870594024658
                   label#F1/Te/a                                   0.5361685156822205
      label#F1/Te/preprocessed_Re-stimulated                       0.6874803304672241
         label#F1/Te/preprocessed_Resting                          0.3848567008972168
               label#Precision/Te/a                                0.8183746337890625
   label#Precision/Te/preprocessed_Re-stimulated                    0.923900306224823
      label#Precision/Te/preprocessed_Resting                      0.7128489017486572
                 label#Recall/Te/a                                 0.43975088000297546
    label#Recall/Te/preprocessed_Re-stimulated                     0.5828461050987244
       label#Recall/Te/preprocessed_Resting                        0.29665565490722656
                     nDCG/Te/a                                     0.9077130556106567
        nDCG/Te/preprocessed_Re-stimulated                         0.9589957594871521
           nDCG/Te/preprocessed_Resting                            0.8564304113388062
                 sample#AUPRC/Te/a                                 0.8795945644378662
    sample#AUPRC/Te/preprocessed_Re-stimulated                     0.9464246034622192
       sample#AUPRC/Te/preprocessed_Resting                        0.8127645254135132
                 sample#AUROC/Te/a                                 0.9864811897277832
    sample#AUROC/Te/preprocessed_Re-stimulated                     0.9934377074241638
       sample#AUROC/Te/preprocessed_Resting                        0.9795244932174683
                sample#F1@Top1/Te/a                                0.8237733244895935
   sample#F1@Top1/Te/preprocessed_Re-stimulated                    0.9185507893562317
      sample#F1@Top1/Te/preprocessed_Resting                       0.7289958000183105
                sample#F1@Top5/Te/a                                0.31724390387535095
   sample#F1@Top5/Te/preprocessed_Re-stimulated                    0.32840484380722046
      sample#F1@Top5/Te/preprocessed_Resting                       0.30608299374580383
            sample#Precision@Top1/Te/a                             0.8237733244895935
sample#Precision@Top1/Te/preprocessed_Re-stimulated                0.9185507893562317
   sample#Precision@Top1/Te/preprocessed_Resting                   0.7289958000183105
            sample#Precision@Top5/Te/a                             0.1903463453054428
sample#Precision@Top5/Te/preprocessed_Re-stimulated                0.19704289734363556
   sample#Precision@Top5/Te/preprocessed_Resting                   0.18364977836608887
              sample#Recall@Top1/Te/a                              0.8237733244895935
 sample#Recall@Top1/Te/preprocessed_Re-stimulated                  0.9185507893562317
    sample#Recall@Top1/Te/preprocessed_Resting                     0.7289958000183105
              sample#Recall@Top5/Te/a                               0.95173180103302
 sample#Recall@Top5/Te/preprocessed_Re-stimulated                  0.9852146506309509
    sample#Recall@Top5/Te/preprocessed_Resting                     0.9182488918304443
────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────

Testing: |          | 0/? [00:00<?, ?it/s]

LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0,1,2]

────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
                    Test metric                                       DataLoader 0
────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
                   ACC@Top1/Te/a                                   0.8259286880493164
      ACC@Top1/Te/preprocessed_Re-stimulated                       0.9225966334342957
         ACC@Top1/Te/preprocessed_Resting                           0.729261040687561
                   ACC@Top5/Te/a                                   0.9502977132797241
      ACC@Top5/Te/preprocessed_Re-stimulated                       0.9863764047622681
         ACC@Top5/Te/preprocessed_Resting                          0.9142190217971802
                   Coverage/Te/a                                   1.9306830167770386
      Coverage/Te/preprocessed_Re-stimulated                       1.4330295324325562
         Coverage/Te/preprocessed_Resting                          2.4283363819122314
                     Lcls/Te/a                                     2.7205257415771484
        Lcls/Te/preprocessed_Re-stimulated                         1.6534874439239502
           Lcls/Te/preprocessed_Resting                            3.7875638008117676
                    Lcls_w/Te/a                                     978.7532958984375
                     Lkld/Te/a                                             0.0
        Lkld/Te/preprocessed_Re-stimulated                                 0.0
           Lkld/Te/preprocessed_Resting                                    0.0
                     Lmix/Te/a                                       3265.373046875
                     Lrec/Te/a                                      717.4556884765625
        Lrec/Te/preprocessed_Re-stimulated                          543.8092041015625
           Lrec/Te/preprocessed_Resting                             891.102294921875
                     Lvae/Te/a                                      717.4556884765625
        Lvae/Te/preprocessed_Re-stimulated                          543.8092041015625
           Lvae/Te/preprocessed_Resting                             891.102294921875
                    Lvae_w/Te/a                                    0.8493526577949524
                     MRR/Te/a                                      0.8809014558792114
         MRR/Te/preprocessed_Re-stimulated                         0.9490624070167542
            MRR/Te/preprocessed_Resting                            0.8127405643463135
                 RankingLoss/Te/a                                  0.01368651445955038
     RankingLoss/Te/preprocessed_Re-stimulated                    0.006368081551045179
        RankingLoss/Te/preprocessed_Resting                       0.021004948765039444
                    RelPos/Te/a                                    0.9863134622573853
       RelPos/Te/preprocessed_Re-stimulated                        0.9936319589614868
          RelPos/Te/preprocessed_Resting                           0.9789950251579285
                 label#AUPRC/Te/a                                  0.9075962901115417
     label#AUPRC/Te/preprocessed_Re-stimulated                     0.9348399639129639
        label#AUPRC/Te/preprocessed_Resting                        0.8803523778915405
                 label#AUROC/Te/a                                  0.9928974509239197
     label#AUROC/Te/preprocessed_Re-stimulated                     0.9945873618125916
        label#AUROC/Te/preprocessed_Resting                        0.9912074208259583
                   label#F1/Te/a                                   0.5283306837081909
      label#F1/Te/preprocessed_Re-stimulated                       0.6843687295913696
         label#F1/Te/preprocessed_Resting                          0.3722926676273346
               label#Precision/Te/a                                0.8026536703109741
   label#Precision/Te/preprocessed_Re-stimulated                   0.9191311597824097
      label#Precision/Te/preprocessed_Resting                      0.6861761808395386
                 label#Recall/Te/a                                 0.4358849823474884
    label#Recall/Te/preprocessed_Re-stimulated                     0.5837205052375793
       label#Recall/Te/preprocessed_Resting                        0.28804948925971985
                     nDCG/Te/a                                     0.9086572527885437
        nDCG/Te/preprocessed_Re-stimulated                         0.9609885811805725
           nDCG/Te/preprocessed_Resting                            0.8563260436058044
                 sample#AUPRC/Te/a                                  0.880901575088501
    sample#AUPRC/Te/preprocessed_Re-stimulated                     0.9490625262260437
       sample#AUPRC/Te/preprocessed_Resting                        0.8127406239509583
                 sample#AUROC/Te/a                                 0.9863134622573853
    sample#AUROC/Te/preprocessed_Re-stimulated                     0.9936319589614868
       sample#AUROC/Te/preprocessed_Resting                        0.9789949655532837
                sample#F1@Top1/Te/a                                0.8259286880493164
   sample#F1@Top1/Te/preprocessed_Re-stimulated                    0.9225966930389404
      sample#F1@Top1/Te/preprocessed_Resting                        0.729261040687561
                sample#F1@Top5/Te/a                                0.3167659342288971
   sample#F1@Top5/Te/preprocessed_Re-stimulated                    0.32879215478897095
      sample#F1@Top5/Te/preprocessed_Resting                       0.30473968386650085
            sample#Precision@Top1/Te/a                             0.8259286880493164
sample#Precision@Top1/Te/preprocessed_Re-stimulated                0.9225966930389404
   sample#Precision@Top1/Te/preprocessed_Resting                    0.729261040687561
            sample#Precision@Top5/Te/a                             0.19005955755710602
sample#Precision@Top5/Te/preprocessed_Re-stimulated                 0.197275310754776
   sample#Precision@Top5/Te/preprocessed_Resting                   0.18284378945827484
              sample#Recall@Top1/Te/a                              0.8259286880493164
 sample#Recall@Top1/Te/preprocessed_Re-stimulated                  0.9225966930389404
    sample#Recall@Top1/Te/preprocessed_Resting                      0.729261040687561
              sample#Recall@Top5/Te/a                              0.9502977132797241
 sample#Recall@Top5/Te/preprocessed_Re-stimulated                  0.9863764047622681
    sample#Recall@Top5/Te/preprocessed_Resting                      0.914219081401825
────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────

Testing: |          | 0/? [00:00<?, ?it/s]

LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0,1,2]

────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
                    Test metric                                       DataLoader 0
────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
                   ACC@Top1/Te/a                                   0.8315961956977844
      ACC@Top1/Te/preprocessed_Re-stimulated                       0.9252164959907532
         ACC@Top1/Te/preprocessed_Resting                          0.7379758358001709
                   ACC@Top5/Te/a                                    0.955947756767273
      ACC@Top5/Te/preprocessed_Re-stimulated                       0.9869576692581177
         ACC@Top5/Te/preprocessed_Resting                          0.9249380826950073
                   Coverage/Te/a                                   1.8870826959609985
      Coverage/Te/preprocessed_Re-stimulated                       1.3927088975906372
         Coverage/Te/preprocessed_Resting                          2.3814568519592285
                     Lcls/Te/a                                      2.666327953338623
        Lcls/Te/preprocessed_Re-stimulated                         1.6455055475234985
           Lcls/Te/preprocessed_Resting                            3.6871495246887207
                    Lcls_w/Te/a                                     978.7532958984375
                     Lkld/Te/a                                             0.0
        Lkld/Te/preprocessed_Re-stimulated                                 0.0
           Lkld/Te/preprocessed_Resting                                    0.0
                     Lmix/Te/a                                      3211.286865234375
                     Lrec/Te/a                                      716.2316284179688
        Lrec/Te/preprocessed_Re-stimulated                          545.1401977539062
           Lrec/Te/preprocessed_Resting                             887.322998046875
                     Lvae/Te/a                                      716.2316284179688
        Lvae/Te/preprocessed_Re-stimulated                          545.1401977539062
           Lvae/Te/preprocessed_Resting                             887.322998046875
                    Lvae_w/Te/a                                    0.8493526577949524
                     MRR/Te/a                                      0.8864481449127197
         MRR/Te/preprocessed_Re-stimulated                         0.9513140320777893
            MRR/Te/preprocessed_Resting                            0.8215822577476501
                 RankingLoss/Te/a                                 0.013045335188508034
     RankingLoss/Te/preprocessed_Re-stimulated                    0.005775129422545433
        RankingLoss/Te/preprocessed_Resting                       0.020315539091825485
                    RelPos/Te/a                                    0.9869546890258789
       RelPos/Te/preprocessed_Re-stimulated                        0.9942249059677124
          RelPos/Te/preprocessed_Resting                           0.9796844124794006
                 label#AUPRC/Te/a                                  0.9119741320610046
     label#AUPRC/Te/preprocessed_Re-stimulated                     0.9377833008766174
        label#AUPRC/Te/preprocessed_Resting                        0.8861648440361023
                 label#AUROC/Te/a                                   0.993669867515564
     label#AUROC/Te/preprocessed_Re-stimulated                     0.9951726198196411
        label#AUROC/Te/preprocessed_Resting                        0.9921671152114868
                   label#F1/Te/a                                   0.5409892797470093
      label#F1/Te/preprocessed_Re-stimulated                       0.6938605904579163
         label#F1/Te/preprocessed_Resting                          0.3881179690361023
               label#Precision/Te/a                                 0.816673219203949
   label#Precision/Te/preprocessed_Re-stimulated                   0.9220848083496094
      label#Precision/Te/preprocessed_Resting                      0.7112615704536438
                 label#Recall/Te/a                                 0.4467768967151642
    label#Recall/Te/preprocessed_Re-stimulated                     0.5913621187210083
       label#Recall/Te/preprocessed_Resting                        0.30219167470932007
                     nDCG/Te/a                                     0.9130257964134216
        nDCG/Te/preprocessed_Re-stimulated                          0.962775468826294
           nDCG/Te/preprocessed_Resting                            0.8632763028144836
                 sample#AUPRC/Te/a                                 0.8864482641220093
    sample#AUPRC/Te/preprocessed_Re-stimulated                     0.9513140916824341
       sample#AUPRC/Te/preprocessed_Resting                        0.8215824365615845
                 sample#AUROC/Te/a                                 0.9869546890258789
    sample#AUROC/Te/preprocessed_Re-stimulated                     0.9942249059677124
       sample#AUROC/Te/preprocessed_Resting                        0.9796844124794006
                sample#F1@Top1/Te/a                                0.8315961360931396
   sample#F1@Top1/Te/preprocessed_Re-stimulated                    0.9252164959907532
      sample#F1@Top1/Te/preprocessed_Resting                       0.7379758358001709
                sample#F1@Top5/Te/a                                0.3186492621898651
   sample#F1@Top5/Te/preprocessed_Re-stimulated                    0.32898589968681335
      sample#F1@Top5/Te/preprocessed_Resting                       0.30831271409988403
            sample#Precision@Top1/Te/a                             0.8315961360931396
sample#Precision@Top1/Te/preprocessed_Re-stimulated                0.9252164959907532
   sample#Precision@Top1/Te/preprocessed_Resting                   0.7379758358001709
            sample#Precision@Top5/Te/a                             0.19118955731391907
sample#Precision@Top5/Te/preprocessed_Re-stimulated                0.19739152491092682
   sample#Precision@Top5/Te/preprocessed_Resting                   0.1849876195192337
              sample#Recall@Top1/Te/a                              0.8315961360931396
 sample#Recall@Top1/Te/preprocessed_Re-stimulated                  0.9252164959907532
    sample#Recall@Top1/Te/preprocessed_Resting                     0.7379758358001709
              sample#Recall@Top5/Te/a                               0.955947756767273
 sample#Recall@Top5/Te/preprocessed_Re-stimulated                  0.9869576692581177
    sample#Recall@Top5/Te/preprocessed_Resting                     0.9249379634857178
────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────

Testing: |          | 0/? [00:00<?, ?it/s]

LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0,1,2]

────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
                    Test metric                                       DataLoader 0
────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
                   ACC@Top1/Te/a                                   0.8243517279624939
      ACC@Top1/Te/preprocessed_Re-stimulated                       0.9237624406814575
         ACC@Top1/Te/preprocessed_Resting                          0.7249411344528198
                   ACC@Top5/Te/a                                   0.9501347541809082
      ACC@Top5/Te/preprocessed_Re-stimulated                       0.9843384027481079
         ACC@Top5/Te/preprocessed_Resting                          0.9159311652183533
                   Coverage/Te/a                                   1.9856311082839966
      Coverage/Te/preprocessed_Re-stimulated                       1.4414865970611572
         Coverage/Te/preprocessed_Resting                           2.529775857925415
                     Lcls/Te/a                                     2.7373509407043457
        Lcls/Te/preprocessed_Re-stimulated                         1.6591241359710693
           Lcls/Te/preprocessed_Resting                            3.8155782222747803
                    Lcls_w/Te/a                                     978.7532958984375
                     Lkld/Te/a                                             0.0
        Lkld/Te/preprocessed_Re-stimulated                                 0.0
           Lkld/Te/preprocessed_Resting                                    0.0
                     Lmix/Te/a                                       3279.6181640625
                     Lrec/Te/a                                      714.8389282226562
        Lrec/Te/preprocessed_Re-stimulated                          540.7161254882812
           Lrec/Te/preprocessed_Resting                             888.9617309570312
                     Lvae/Te/a                                      714.8389282226562
        Lvae/Te/preprocessed_Re-stimulated                          540.7161254882812
           Lvae/Te/preprocessed_Resting                             888.9617309570312
                    Lvae_w/Te/a                                    0.8493526577949524
                     MRR/Te/a                                       0.879263162612915
         MRR/Te/preprocessed_Re-stimulated                         0.9491216540336609
            MRR/Te/preprocessed_Resting                            0.8094047904014587
                 RankingLoss/Te/a                                  0.01449457835406065
     RankingLoss/Te/preprocessed_Re-stimulated                     0.00649245036765933
        RankingLoss/Te/preprocessed_Resting                       0.022496705874800682
                    RelPos/Te/a                                    0.9855054616928101
       RelPos/Te/preprocessed_Re-stimulated                        0.9935076236724854
          RelPos/Te/preprocessed_Resting                           0.9775032997131348
                 label#AUPRC/Te/a                                  0.9043169021606445
     label#AUPRC/Te/preprocessed_Re-stimulated                     0.9320236444473267
        label#AUPRC/Te/preprocessed_Resting                         0.876610279083252
                 label#AUROC/Te/a                                   0.992641270160675
     label#AUROC/Te/preprocessed_Re-stimulated                     0.9943971037864685
        label#AUROC/Te/preprocessed_Resting                        0.9908854365348816
                   label#F1/Te/a                                   0.5353235006332397
      label#F1/Te/preprocessed_Re-stimulated                       0.6894470453262329
         label#F1/Te/preprocessed_Resting                          0.38120001554489136
               label#Precision/Te/a                                0.8177653551101685
   label#Precision/Te/preprocessed_Re-stimulated                   0.9315424561500549
      label#Precision/Te/preprocessed_Resting                      0.7039881944656372
                 label#Recall/Te/a                                 0.43974968791007996
    label#Recall/Te/preprocessed_Re-stimulated                     0.5860791802406311
       label#Recall/Te/preprocessed_Resting                        0.2934202253818512
                     nDCG/Te/a                                     0.9073440432548523
        nDCG/Te/preprocessed_Re-stimulated                         0.9609779715538025
           nDCG/Te/preprocessed_Resting                            0.8537100553512573
                 sample#AUPRC/Te/a                                 0.8792633414268494
    sample#AUPRC/Te/preprocessed_Re-stimulated                     0.9491217732429504
       sample#AUPRC/Te/preprocessed_Resting                        0.8094049096107483
                 sample#AUROC/Te/a                                 0.9855054616928101
    sample#AUROC/Te/preprocessed_Re-stimulated                     0.9935076236724854
       sample#AUROC/Te/preprocessed_Resting                        0.9775032997131348
                sample#F1@Top1/Te/a                                0.8243517279624939
   sample#F1@Top1/Te/preprocessed_Re-stimulated                    0.9237624406814575
      sample#F1@Top1/Te/preprocessed_Resting                       0.7249411344528198
                sample#F1@Top5/Te/a                                0.3167116045951843
   sample#F1@Top5/Te/preprocessed_Re-stimulated                    0.32811278104782104
      sample#F1@Top5/Te/preprocessed_Resting                       0.30531036853790283
            sample#Precision@Top1/Te/a                             0.8243517279624939
sample#Precision@Top1/Te/preprocessed_Re-stimulated                0.9237624406814575
   sample#Precision@Top1/Te/preprocessed_Resting                   0.7249411344528198
            sample#Precision@Top5/Te/a                             0.19002695381641388
sample#Precision@Top5/Te/preprocessed_Re-stimulated                0.1968676745891571
   sample#Precision@Top5/Te/preprocessed_Resting                   0.18318620324134827
              sample#Recall@Top1/Te/a                              0.8243517279624939
 sample#Recall@Top1/Te/preprocessed_Re-stimulated                  0.9237624406814575
    sample#Recall@Top1/Te/preprocessed_Resting                     0.7249411344528198
              sample#Recall@Top5/Te/a                              0.9501347541809082
 sample#Recall@Top5/Te/preprocessed_Re-stimulated                  0.9843384623527527
    sample#Recall@Top5/Te/preprocessed_Resting                      0.915931224822998
────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────

Testing: |          | 0/? [00:00<?, ?it/s]

LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0,1,2]

────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
                    Test metric                                       DataLoader 0
────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
                   ACC@Top1/Te/a                                   0.8248853087425232
      ACC@Top1/Te/preprocessed_Re-stimulated                       0.9156501293182373
         ACC@Top1/Te/preprocessed_Resting                          0.7341206669807434
                   ACC@Top5/Te/a                                   0.9501251578330994
      ACC@Top5/Te/preprocessed_Re-stimulated                       0.9811620116233826
         ACC@Top5/Te/preprocessed_Resting                          0.9190883040428162
                   Coverage/Te/a                                   1.9839885234832764
      Coverage/Te/preprocessed_Re-stimulated                       1.4999442100524902
         Coverage/Te/preprocessed_Resting                          2.4680328369140625
                     Lcls/Te/a                                      2.696129083633423
        Lcls/Te/preprocessed_Re-stimulated                         1.7092558145523071
           Lcls/Te/preprocessed_Resting                            3.6830027103424072
                    Lcls_w/Te/a                                     978.7532958984375
                     Lkld/Te/a                                             0.0
        Lkld/Te/preprocessed_Re-stimulated                                 0.0
           Lkld/Te/preprocessed_Resting                                    0.0
                     Lmix/Te/a                                      3239.02978515625
                     Lrec/Te/a                                      714.5528564453125
        Lrec/Te/preprocessed_Re-stimulated                          543.997314453125
           Lrec/Te/preprocessed_Resting                              885.1083984375
                     Lvae/Te/a                                      714.5528564453125
        Lvae/Te/preprocessed_Re-stimulated                          543.997314453125
           Lvae/Te/preprocessed_Resting                              885.1083984375
                    Lvae_w/Te/a                                    0.8493526577949524
                     MRR/Te/a                                      0.8803154230117798
         MRR/Te/preprocessed_Re-stimulated                         0.9440360069274902
            MRR/Te/preprocessed_Resting                            0.8165949583053589
                 RankingLoss/Te/a                                 0.014470421709120274
     RankingLoss/Te/preprocessed_Re-stimulated                    0.007352122105658054
        RankingLoss/Te/preprocessed_Resting                       0.021588720381259918
                    RelPos/Te/a                                    0.9855296015739441
       RelPos/Te/preprocessed_Re-stimulated                        0.9926479458808899
          RelPos/Te/preprocessed_Resting                           0.9784112572669983
                 label#AUPRC/Te/a                                  0.9089921712875366
     label#AUPRC/Te/preprocessed_Re-stimulated                     0.9295324087142944
        label#AUPRC/Te/preprocessed_Resting                        0.8884517550468445
                 label#AUROC/Te/a                                  0.9924827814102173
     label#AUROC/Te/preprocessed_Re-stimulated                     0.9935733675956726
        label#AUROC/Te/preprocessed_Resting                        0.9913922548294067
                   label#F1/Te/a                                   0.5381175875663757
      label#F1/Te/preprocessed_Re-stimulated                       0.6873881220817566
         label#F1/Te/preprocessed_Resting                          0.3888470530509949
               label#Precision/Te/a                                0.8066044449806213
   label#Precision/Te/preprocessed_Re-stimulated                   0.9184018969535828
      label#Precision/Te/preprocessed_Resting                      0.6948069334030151
                 label#Recall/Te/a                                  0.444042444229126
    label#Recall/Te/preprocessed_Re-stimulated                     0.5868328809738159
       label#Recall/Te/preprocessed_Resting                        0.30125197768211365
                     nDCG/Te/a                                     0.9081568121910095
        nDCG/Te/preprocessed_Re-stimulated                          0.957062840461731
           nDCG/Te/preprocessed_Resting                             0.859250545501709
                 sample#AUPRC/Te/a                                 0.8803155422210693
    sample#AUPRC/Te/preprocessed_Re-stimulated                     0.9440360069274902
       sample#AUPRC/Te/preprocessed_Resting                        0.8165950179100037
                 sample#AUROC/Te/a                                 0.9855296611785889
    sample#AUROC/Te/preprocessed_Re-stimulated                     0.9926478862762451
       sample#AUROC/Te/preprocessed_Resting                        0.9784114360809326
                sample#F1@Top1/Te/a                                 0.824885368347168
   sample#F1@Top1/Te/preprocessed_Re-stimulated                    0.9156501293182373
      sample#F1@Top1/Te/preprocessed_Resting                       0.7341206669807434
                sample#F1@Top5/Te/a                                0.31670838594436646
   sample#F1@Top5/Te/preprocessed_Re-stimulated                    0.3270540237426758
      sample#F1@Top5/Te/preprocessed_Resting                       0.30636274814605713
            sample#Precision@Top1/Te/a                              0.824885368347168
sample#Precision@Top1/Te/preprocessed_Re-stimulated                0.9156501293182373
   sample#Precision@Top1/Te/preprocessed_Resting                   0.7341206669807434
            sample#Precision@Top5/Te/a                             0.19002503156661987
sample#Precision@Top5/Te/preprocessed_Re-stimulated                 0.196232408285141
   sample#Precision@Top5/Te/preprocessed_Resting                   0.18381765484809875
              sample#Recall@Top1/Te/a                               0.824885368347168
 sample#Recall@Top1/Te/preprocessed_Re-stimulated                  0.9156501293182373
    sample#Recall@Top1/Te/preprocessed_Resting                     0.7341206669807434
              sample#Recall@Top5/Te/a                              0.9501251578330994
 sample#Recall@Top5/Te/preprocessed_Re-stimulated                  0.9811620116233826
    sample#Recall@Top5/Te/preprocessed_Resting                     0.9190883040428162
────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────

Testing: |          | 0/? [00:00<?, ?it/s]

────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
                    Test metric                                       DataLoader 0
────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
                   ACC@Top1/Te/a                                   0.8319132924079895
      ACC@Top1/Te/preprocessed_Re-stimulated                        0.923243522644043
         ACC@Top1/Te/preprocessed_Resting                          0.7405830025672913
                   ACC@Top5/Te/a                                   0.9520154595375061
      ACC@Top5/Te/preprocessed_Re-stimulated                       0.9849326014518738
         ACC@Top5/Te/preprocessed_Resting                          0.9190983772277832
                   Coverage/Te/a                                   1.9132779836654663
      Coverage/Te/preprocessed_Re-stimulated                       1.4193601608276367
         Coverage/Te/preprocessed_Resting                           2.407195806503296
                     Lcls/Te/a                                      2.682633876800537
        Lcls/Te/preprocessed_Re-stimulated                         1.6684898138046265
           Lcls/Te/preprocessed_Resting                            3.6967785358428955
                    Lcls_w/Te/a                                     978.7532958984375
                     Lkld/Te/a                                             0.0
        Lkld/Te/preprocessed_Re-stimulated                                 0.0
           Lkld/Te/preprocessed_Resting                                    0.0
                     Lmix/Te/a                                       3228.6005859375
                     Lrec/Te/a                                      717.8252563476562
        Lrec/Te/preprocessed_Re-stimulated                          544.4044189453125
           Lrec/Te/preprocessed_Resting                             891.2462768554688
                     Lvae/Te/a                                      717.8252563476562
        Lvae/Te/preprocessed_Re-stimulated                          544.4044189453125
           Lvae/Te/preprocessed_Resting                             891.2462768554688
                    Lvae_w/Te/a                                    0.8493526577949524
                     MRR/Te/a                                       0.884869396686554
         MRR/Te/preprocessed_Re-stimulated                         0.9488083720207214
            MRR/Te/preprocessed_Resting                            0.8209304809570312
                 RankingLoss/Te/a                                 0.013430559076368809
     RankingLoss/Te/preprocessed_Re-stimulated                    0.006167062558233738
        RankingLoss/Te/preprocessed_Resting                       0.020694056525826454
                    RelPos/Te/a                                    0.9865694046020508
       RelPos/Te/preprocessed_Re-stimulated                        0.9938328862190247
          RelPos/Te/preprocessed_Resting                           0.9793059229850769
                 label#AUPRC/Te/a                                  0.9101751446723938
     label#AUPRC/Te/preprocessed_Re-stimulated                     0.9333161115646362
        label#AUPRC/Te/preprocessed_Resting                        0.8870341777801514
                 label#AUROC/Te/a                                   0.992660641670227
     label#AUROC/Te/preprocessed_Re-stimulated                     0.9942570328712463
        label#AUROC/Te/preprocessed_Resting                        0.9910640120506287
                   label#F1/Te/a                                   0.5291310548782349
      label#F1/Te/preprocessed_Re-stimulated                        0.676364541053772
         label#F1/Te/preprocessed_Resting                          0.3818976581096649
               label#Precision/Te/a                                0.8128477931022644
   label#Precision/Te/preprocessed_Re-stimulated                    0.917529284954071
      label#Precision/Te/preprocessed_Resting                       0.708166241645813
                 label#Recall/Te/a                                 0.4333096146583557
    label#Recall/Te/preprocessed_Re-stimulated                     0.5717143416404724
       label#Recall/Te/preprocessed_Resting                        0.2949049472808838
                     nDCG/Te/a                                     0.9116732478141785
        nDCG/Te/preprocessed_Re-stimulated                          0.960791289806366
           nDCG/Te/preprocessed_Resting                            0.8625550866127014
                 sample#AUPRC/Te/a                                 0.8848695158958435
    sample#AUPRC/Te/preprocessed_Re-stimulated                     0.9488085508346558
       sample#AUPRC/Te/preprocessed_Resting                         0.820930540561676
                 sample#AUROC/Te/a                                 0.9865694642066956
    sample#AUROC/Te/preprocessed_Re-stimulated                     0.9938330054283142
       sample#AUROC/Te/preprocessed_Resting                        0.9793061017990112
                sample#F1@Top1/Te/a                                0.8319132924079895
   sample#F1@Top1/Te/preprocessed_Re-stimulated                    0.9232435822486877
      sample#F1@Top1/Te/preprocessed_Resting                       0.7405830025672913
                sample#F1@Top5/Te/a                                0.3173385262489319
   sample#F1@Top5/Te/preprocessed_Re-stimulated                    0.32831090688705444
      sample#F1@Top5/Te/preprocessed_Resting                       0.3063661456108093
            sample#Precision@Top1/Te/a                             0.8319132924079895
sample#Precision@Top1/Te/preprocessed_Re-stimulated                0.9232435822486877
   sample#Precision@Top1/Te/preprocessed_Resting                   0.7405830025672913
            sample#Precision@Top5/Te/a                             0.19040308892726898
sample#Precision@Top5/Te/preprocessed_Re-stimulated                0.19698652625083923
   sample#Precision@Top5/Te/preprocessed_Resting                   0.18381968140602112
              sample#Recall@Top1/Te/a                              0.8319132924079895
 sample#Recall@Top1/Te/preprocessed_Re-stimulated                  0.9232435822486877
    sample#Recall@Top1/Te/preprocessed_Resting                     0.7405830025672913
              sample#Recall@Top5/Te/a                              0.9520154595375061
 sample#Recall@Top5/Te/preprocessed_Re-stimulated                  0.9849326014518738
    sample#Recall@Top5/Te/preprocessed_Resting                      0.919098436832428
────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────

## obtain predicted probabilities for each cell

Here we only predict Schmidt dataset and Norman dataset for reproducing the figures in paper.

In [ ]:
from driver_genes.bmutils import label_metrics, double_relpos_distribution

In [ ]:
expr_list = [
    "../results/benchmarking/schmidt/resting", 
    "../results/benchmarking/schmidt/stimulated", 
    "../results/benchmarking/norman/combo_seensinglesbetter"
]

In [ ]:
for expr_prefix in expr_list:
    expr_dir = f'{expr_prefix}-seed42'
    os.makedirs(f'{expr_dir}/results', exist_ok=True)
    # load fitted model to predict and not aggregating results
    pp = Pipeline(config_path=os.path.join(expr_dir, 'config.yaml'), fitted=True)
    metrics_df, test_pred_adatas_list = pp.evaluate(num_results=5, seed=42, concat=False)
    results_df_dict = {}
    for i, test_pred_adatas in enumerate(test_pred_adatas_list):
        for ad_name, ad in test_pred_adatas.items():
            ad = ad[ad.obs['perturbation'] != 'control']
            results_df_dict[ad_name] = results_df_dict.get(ad_name, [])
            results_df_dict[ad_name].append(ad.obsm['proba'].assign(perturbation=ad.obs['perturbation'], rep=i))
    for ad_name, results_df_list in results_df_dict.items():
        results_df = pd.concat(results_df_list, axis=0, ignore_index=True)
        results_df.to_parquet(os.path.join(expr_dir, f'results/{ad_name}_results.parquet'), index=False)

In [ ]:
task_dict = {
    # (Dataset, Test on)
    ('Schmidt', 'Resting'): {
        'Ours': '../results/benchmarking/schmidt/stimulated-seed42/results/preprocessed_Resting_results.parquet',
        # path to results from other methods
    },
    ('Schmidt', 'Re-stimulated'): {
        'Ours': '../results/benchmarking/schmidt/resting-seed42/results/preprocessed_Re-stimulated_results.parquet',
        # path to results from other methods
    },
    ('Norman', 'Single'): {
        'Ours': '../results/benchmarking/norman/combo_seensinglesbetter-seed42/results/preprocessed_single_results.parquet',
        # path to results from other methods
    },
    ('Norman', 'Combo'): {
        'Ours': '../results/benchmarking/norman/combo_seensinglesbetter-seed42/results/preprocessed_combo_results.parquet',
        # path to results from other methods
    },
}

In [ ]:
results_dict = {}
for (dataset, cell_type), res_path_dict in task_dict.items():
    res_list = []
    for method, res_path in res_path_dict.items():
        results_df = pd.read_parquet(res_path)
        res_list.append(results_df.assign(method=method))
    results_dict[(dataset, cell_type)] = pd.concat(res_list)
pd.to_pickle(results_dict, 'data/results_dict_runtime.pkl')

In [ ]:
def group_apply(subres_df):
    unness_cols = list(set(subres_df.columns) & set(['perturbation', 'rep', 'method']))
    score_df = subres_df.drop(columns=unness_cols)
    perturbations = subres_df['perturbation']
    metrics = label_metrics(score_df, perturbations)
    return metrics

### Schmidt dataset

In [ ]:
results_df = pd.concat([
    results_dict[('Schmidt', 'Resting')].assign(cell_type='Resting'),
    results_dict[('Schmidt', 'Re-stimulated')].assign(cell_type='Re-stimulated'),
])
label_metrics_df = (
    results_df
    .groupby(['cell_type', 'method', 'rep'])
    .apply(group_apply, include_groups=False)
    .reset_index()
    .groupby(['cell_type', 'method', 'perturbation'])
    .agg(['mean', 'std'])
    .reset_index()
    .drop(columns=['rep', 'level_3'])
)

In [ ]:
other_metrics_df = pd.read_pickle('data/schmidt_label_metrics_df.pkl')
# filter out the metrics of our model from the previous runnings
other_metrics_df = other_metrics_df.query('Method != "Ours"')
all_metrics_df = pd.concat([
    other_metrics_df,
    label_metrics_df
])
label_metrics_df.to_pickle('data/schmidt_label_metrics_df.pkl')

In [ ]:
label_metrics_df

         cell_type method perturbation       auc              relpos  \
                                            mean       std      mean
0    Re-stimulated    CPA       ABCB10  0.570268  0.038526  0.730899
1    Re-stimulated    CPA       AKAP12  0.436179  0.022437  0.178435
2    Re-stimulated    CPA         ALX4  0.477314  0.018935  0.392870
3    Re-stimulated    CPA     APOBEC3C  0.406364  0.026038  0.665623
4    Re-stimulated    CPA     APOBEC3D  0.419661  0.038156  0.701333
..             ...    ...          ...       ...       ...       ...
823        Resting   Ours      TNFRSF9  0.792787  0.021266  0.843304
824        Resting   Ours     TRAF3IP2  0.828332  0.053083  0.870609
825        Resting   Ours       TRIM21  0.714681  0.021880  0.873797
826        Resting   Ours         VAV1  0.778823  0.020483  0.735768
827        Resting   Ours          WT1  0.905643  0.021461  0.930029

              top1acc           top5recall
          std    mean       std       mean       std
0    0.012429   0.008  0.010954      0.064  0.021909
1    0.040287   0.000  0.000000      0.040  0.024495
2    0.024132   0.000  0.000000      0.000  0.000000
3    0.022644   0.012  0.010954      0.052  0.030332
4    0.038828   0.096  0.008944      0.576  0.058992
..        ...     ...       ...        ...       ...
823  0.018380   0.288  0.036332      0.456  0.076681
824  0.038290   0.396  0.084143      0.604  0.065422
825  0.010061   0.216  0.026077      0.524  0.038471
826  0.030410   0.096  0.035777      0.280  0.054772
827  0.013113   0.696  0.047749      0.796  0.040988

[828 rows x 11 columns]

### Norman dataset

In [ ]:
def group_apply(subres_df):
    unness_cols = list(set(subres_df.columns) & set(['perturbation', 'rep', 'method']))
    score_df = subres_df.drop(columns=unness_cols)
    perturbations = subres_df['perturbation']
    relpos = double_relpos_distribution(score_df, perturbations)
    return relpos

In [ ]:
results_df = results_dict[('Norman', 'Combo')]
relpos_df = (
    results_df
    .groupby(['method'])
    .apply(group_apply, include_groups=False)
    .reset_index()
    .drop(columns=['level_1'])
)

In [ ]:
other_relpos_df = pd.read_pickle('data/norman_relpos_df.pkl')
# filter out the relpos of our model from the previous runnings
other_relpos_df = other_relpos_df.query('Method != "Ours"')
all_relpos_df = pd.concat([
    other_relpos_df,
    relpos_df
])
all_relpos_df.to_pickle('data/norman_relpos_df.pkl')

In [ ]:
relpos_df

       method     gene1     gene2
0         CPA  0.657143  0.628571
1         CPA  0.561905  0.380952
2         CPA  0.980952  0.438095
3         CPA  0.714286  0.419048
4         CPA  0.771429  0.409524
...       ...       ...       ...
200630   Ours  0.990476  0.761905
200631   Ours  1.000000  0.342857
200632   Ours  0.771429  0.723810
200633   Ours  0.990476  0.952381
200634   Ours  1.000000  0.895238

[200635 rows x 3 columns]